//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSRDAL.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbEntities : DbContext
    {
        public DbEntities()
            : base("name=DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<JiraTickets> JiraTickets { get; set; }
        public virtual DbSet<Months> Months { get; set; }
        public virtual DbSet<SubTasks> SubTasks { get; set; }
        public virtual DbSet<Tasks> Tasks { get; set; }
        public virtual DbSet<TaskStatus> TaskStatus { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Years> Years { get; set; }
        public virtual DbSet<HelpDeskTickets> HelpDeskTickets { get; set; }
        public virtual DbSet<WebTrendLinkData> WebTrendLinkData { get; set; }
        public virtual DbSet<WebTrendResourceData> WebTrendResourceData { get; set; }
        public virtual DbSet<WebTrendSiteData> WebTrendSiteData { get; set; }
        public virtual DbSet<WebTrendTermData> WebTrendTermData { get; set; }
        public virtual DbSet<Type> Type { get; set; }
    }
}
