//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSRDAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public int MonthId { get; set; }
        public int Year { get; set; }
        public Nullable<int> Type { get; set; }
        public int StatusId { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public virtual ICollection<SubTasks> SubTasks { get; set; }
        public virtual TaskStatus TaskStatus { get; set; }
        public virtual Users Users { get; set; }
    }
}
